import { CHUNK_RADIUS, defaultServerUrl } from "./config.js";

export const state = {
  mode: "menu",
  gamemode: "survival",
  mouseSensitivity: 1,
  fov: 75,
  viewRadius: CHUNK_RADIUS,
  unlimitedViewDistance: false,
  movementSpeed: 1,
  flySpeed: 1,
  lastTime: 0,
  manualTime: false,
  timeOfDay: 0.25,
  debugHud: false,
  optionsOpen: false,
  targetedBlock: null,
  targetedFace: null,
  targetedMob: null,
  targetedPlayer: null,
  blocks: 0,
  inventoryOpen: false,
  craftingTableOpen: false,
  chatOpen: false,
  selectedHotbar: 0,
  heldItem: null,
  dragging: false,
  dragMoved: false,
  dragButton: null,
  dragStartX: 0,
  dragStartY: 0,
  mining: {
    active: false,
    progress: 0,
    targetKey: null,
    blockType: null,
  },
  currentChunkX: null,
  currentChunkZ: null,
  currentViewRadius: null,
  worldInitialized: false,
  respawnPoint: null,
  multiplayer: {
    enabled: false,
    connected: false,
    isHost: false,
    room: null,
    name: "Player",
    serverUrl: defaultServerUrl,
  },
};
