export const state = {
  mode: "menu",
  gamemode: "survival",
  lastTime: 0,
  manualTime: false,
  timeOfDay: 0.25,
  debugHud: false,
  targetedBlock: null,
  targetedFace: null,
  targetedMob: null,
  blocks: 0,
  inventoryOpen: false,
  craftingTableOpen: false,
  chatOpen: false,
  selectedHotbar: 0,
  heldItem: null,
  dragging: false,
  dragMoved: false,
  dragButton: null,
  dragStartX: 0,
  dragStartY: 0,
  mining: {
    active: false,
    progress: 0,
    targetKey: null,
    blockType: null,
  },
  currentChunkX: null,
  currentChunkZ: null,
  worldInitialized: false,
  respawnPoint: null,
};
